language: php
php:
  - '7.0'
  - hhvm
before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo hhvm.enable_hip_hop_syntax=1 >> /etc/hhvm/php.ini; fi'
  - composer self-update
  - composer install --prefer-source --no-interaction --ignore-platform-reqs
script:
  - vendor/bin/phpunit
  - vendor/bin/phpmd src/ text phpmd.xml
